name: Weekly Slack Bot

on:
  schedule:
    # Runs every Monday at 08:00 UTC
    - cron: '0 8 * * 1'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  post-weekly-message:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Slack bot
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: python slack_bot.py
      
    - name: Log completion
      if: success()
      run: echo "Weekly Slack message posted successfully!"
      
    - name: Log failure
      if: failure()
      run: echo "Failed to post weekly Slack message. Check logs above for details."